"""Added name column to round table

Revision ID: 145bd741b680
Revises: fa3f39af87c2
Create Date: 2024-01-25 21:08:36.742948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145bd741b680'
down_revision = 'fa3f39af87c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('number')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('number', sa.INTEGER(), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
