"""Added round_id to game

Revision ID: fa3f39af87c2
Revises: 
Create Date: 2024-01-25 20:18:13.574084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3f39af87c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_round_id', 'round', ['round_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:

        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('round_id')

    # ### end Alembic commands ###